use_frameworks!

platform :ios, '9.0'

target 'YLDashLineView_Example' do
  pod 'YLDashLineView', :path => '../'

  target 'YLDashLineView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
